### ISSUE TITLE
USER STORY: Django installation and project setup

### ISSUE THREAD

**Issue by KevinFlanagan7** [KevinFlanagan7/PP4-booking-system#1]
EPIC: **Initial Setup**

As a **developer** I can **install Django and and complete all required initial setup** so that **development of project can begin**

**Acceptance Criteria**

- [x] AC1: When Django server is run a simple welcome message is displayed in the browser.

**Tasks**

- [x] Task 1: Create Repository 
- [x]  Task 2: Install Django package
- [x]  Task 3: Create requirements file
- [x]  Task 4: Create project and app
- [x]  Task 5: Add app to settings.py
- [x]  Task 6: Run Django server to test project in the browser
