### ISSUE TITLE
USER STORY: Deploy project to Heroku

### ISSUE THREAD

**Issue by KevinFlanagan7** [KevinFlanagan7/PP4-booking-system#2]
EPIC: **Initial Setup**

As a **developer** I can **deploy project** so that **it can be viewed on Heroku**.

**Acceptance Criteria**

- [x] AC1: When link to deployed site on heroku is clicked the welcome message is displayed in the browser.

**Tasks**

- [x] Task 1: Create new app on Heroku and add config var.
- [x] Task 2: Install gunicorn and add to requirements.txt.
- [x] Task 3: Create Procfile with command heroku will use to start the server.
- [x] Task 4: Set debug to False in settings.py and add heroku hostname to allowed hosts.
- [x] Task 5: Commit changes and connect to repository on deploy tab of heroku app.
- [x] Task 6: Deploy Branch and open app once built.
