### ISSUE TITLE
USER STORY: Creating the database

### ISSUE THREAD

**Issue by KevinFlanagan7** [KevinFlanagan7/PP4-booking-system#3]
EPIC: **Initial Setup**

As a **developer** I can **create a database** so that **data can be entered by the user**.

**Acceptance Criteria**

- [x] AC1: When project app is opened on heroku the database is connected and login as admin user is successful.

**Tasks**

- [x] Task 1: Login to ElephantSQL and create a new instance.
- [x] Task 2: Create env.py file and add to .gitignore file.
- [x] Task 3: Import python's os module and set value of database url.
- [x] Task 4: Install packages to connect to database and add to requirements.txt.
- [x] Task 5: Import packages in settings.py file and connect to database url.
- [x] Task 6: Migrate changes and create database superuser.
- [x] Task 7: Commit to GitHub and deploy 
- [x] Task 8: Update config vars on heroku.
