### ISSUE TITLE
USER STORY: Administrator Setup to mange bookings and user feedback.

### ISSUE THREAD

**Issue by KevinFlanagan7** [KevinFlanagan7/PP4-booking-system#4]
EPIC: **Initial Setup**

As an **Administrator** I can **manage bookings and user feedback** so that **quality of lessons can be maintained**.

**Acceptance Criteria**

- [x] AC1 Administrator has full CRUD capabilities to mange bookings and user feedback.

**Tasks**

- [x] Task 1: Create Entity-Relationship Diagram (ERD) schema for bookings and feedback.
- [x] Task 2: Create Django models for bookings and feedback.
- [x] Task 3: Migrate database.
