### ISSUE TITLE
USER STORY: Ceate Homepage

### ISSUE THREAD

**Issue by KevinFlanagan7** [KevinFlanagan7/PP4-booking-system#5]
EPIC: **Create Homepage**

As a **user**, I can **access the home page** so I can **get information about the golf lessons**.

**Acceptance Criteria**

- [x] AC1 The landing page is opened successfully.

**Tasks**

- [x] Task 1: Create base.html template.
- [x] Task 2: Create index.html template.
- [x] Task 3: Create static files directory.
- [x] Task 4: Update setting.py file.
- [x] Task 5: Enable serving of static files for deployment.
- [x] Task 6: Update urls.py file.
- [x] Task 7: Update views.py file.
