### ISSUE TITLE
USER STORY: Account Registration

### ISSUE THREAD

**Issue by KevinFlanagan7** [KevinFlanagan7/PP4-booking-system#6]
EPIC: **Account Registration**

As a **user** I can **register an account** so that **I can login, make a booking, give feedback and logout**

**Acceptance Criteria**

AC1: The user can create an account, login, make a booking, give feedback and logout.

**Tasks**

- [ ] Task 1: Install Django-Allauth and add to requirements.txt file.
- [ ] Task 2: Edit settings.py file.
- [ ] Task 3: Edit urls.py file.
- [ ] Task 4: Copy the Allauth template files to the projects templates directory.
- [ ] Task 5: Customize Allauth templates.
