### ISSUE TITLE
USER STORY: Registered user Bookings Management

### ISSUE THREAD

**Issue by KevinFlanagan7** [KevinFlanagan7/PP4-booking-system#7]
EPIC: **Registered user Bookings Management**

As a **registered user** I can **create, read, update and delete bookings** so that **the user can fully manage their bookings**.

**Acceptance Criteria**

- [x] AC1: The registered user can create bookings.
- [x] AC2: The registered user can view/read their bookings.
- [x] AC3: The registered user can update bookings.
- [x] AC4: The registered user can delete bookings.

**Tasks**

- [x] Task 1: Create booking_details.html template to view bookings.
- [x] Task 2: Update views.py with function views to list bookings, create, update and delete bookings.
- [x] Task 3: Create html templates for creating, updating and deleting bookings.
- [x] Task 4: Update urls.py with new html templates.
- [x] Task 5: Install crispy forms package and create forms.py file with BookingForm class to connect to Booking model fields.
