### ISSUE TITLE
USER STORY: User-Friendly Website Design

### ISSUE THREAD

**Issue by KevinFlanagan7** [KevinFlanagan7/PP4-booking-system#8]
EPIC:  **Implement and Enhance Website Styling**

As a **user** I want **a visually appealing and easy-to-navigate website** so that **I can have a pleasant and intuitive experience while using the site**.

**Acceptance Criteria**

- [x] AC1: All pages to have a consistent theme which is visually appealing.
- [x] AC2: Navigation should be intuitive and easily accessible.

**Tasks**

- [x] Task 1: Style base.html template using bootstrap and css (header, navigation and footer).
- [x] Task 2: Style Index.html with main homepage content and information.
- [x] Task 3: Style Sign up, Sign in and Sign out pages.
- [x] Task 4: Style booking CRUD pages so all pages have consistent theme.
