### ISSUE TITLE
USER STORY: Receive Email Confirmation for Bookings.

### ISSUE THREAD

**Issue by KevinFlanagan7** [KevinFlanagan7/PP4-booking-system#9]
EPIC: **Email confirmation for bookings**.

As a **user** I can **receive an email confirmation when I create or update a booking ** so that **I have a record of my upcoming booking**.

**Acceptance Criteria**

- [x] When a user books or updates a golf lesson, an email is sent to their registered email address.
- [x] The email includes the date and time the lesson.

**Tasks**

- [x] Configure Django's email sending framework in settings.py.
- [x] Create an email_confirmation.html template for new or updated bookings.
- [x] Create gmail email account of golflessons2024@gmail.com as sender.
- [x] Update settings.py and env.py with gmail account settings.
- [x] Update views.py file to trigger sending email when booking is created or updated.
